dist: trusty
language: elixir

jobs:
  include:
    - elixir: '1.9.0'
      otp_release: '21.0'
    - elixir: '1.10.0'
      otp_release: '22.0'
    - elixir: '1.11.0'
      otp_release: '23.0'
    - elixir: '1.14.1'
      otp_release: '25.2.2'      


script: |
  mix format --check-formatted
  mix test
